
VERSION=1.7
DEBUG_WITHOUT_DOWNLOAD=False

SHOW_MSG=True

CLOSE_BROWSER_ON_FINISHED=True
RETRY_ON_ERRORS_AFTER_DOWNLOAD_FINISHED=True

SUMMARY_MARK='[SUMMARY]'  # in the log file, summary begins with it, at the end of log
HEADER_FULLNAME='FULLNAME' # HEADER OF THE COLUMN
HEADER_INDEX='INDEX'
HEADER_STATUS='STATUS'
HEADER_INDEXED_SHORTNAME='INDEXED_SHORTNAME'
HEADER_SRC='SRC'
HEADER_ERROR_MESSAGE='ERROR_MESSAGE'
STATUS_OK='OK'
STATUS_ERROR='ER'

INDEX_DIGITS=3
SHORT_SLEEP=1
MID_SLEEP=3
BROWSER_IMPLICITLY_WAIT=5
LONG_SLEEP=10

NAME_MAX_LENGTH=60  # FOR shortname
TEXT_MAX_LENGTH=300 # for error msg

LOGGER_EMPTY_PLACEHOLDER='-' # when no content of the cell, use it to write to the cell

XPATH_DOWNLOAD="//a[@data-clip-position and contains(@id, 'lnk')]"


FLAG_URL='-u'
FLAG_PASS='-P'
FLAG_USER='-U'
FLAG_REDO='-r'
FLAG_HELP='-h'

GET_SRC_TRY_MAX=7
SCROLL_HEIGHT=30
