#   config var, put here for now 
VERSION=1.8
DEBUG_WITHOUT_DOWNLOAD=False

GET_SRC_TRY_MAX=7
SCROLL_HEIGHT=30
SHOW_MSG=True
CLOSE_BROWSER_ON_FINISHED=True
RETRY_ON_ERRORS_AFTER_DOWNLOAD_FINISHED=True

INDEX_DIGITS=3
SHORT_SLEEP=1
MID_SLEEP=3
BROWSER_IMPLICITLY_WAIT=5
LONG_SLEEP=10

SUMMARY_MARK='[SUMMARY]'  # in the log file, summary begins with it, at the end of log
HEADER_FULLNAME='FULLNAME' # HEADER OF THE COLUMN
HEADER_INDEX='INDEX'
HEADER_STATUS='STATUS'
HEADER_INDEXED_SHORTNAME='INDEXED_SHORTNAME'
HEADER_SRC='SRC'
HEADER_ERROR_MESSAGE='ERROR_MESSAGE'

STATUS_OK='OK'
STATUS_ERROR='ER'

NAME_MAX_LENGTH=150 # FOR shortname  000_<shortname>.mp4, be careful for windows max length of file path 255
NAME_CHAR_REPLACEMENT=''  # ILLEGAL CHAR
NAME_SUFIX='_'
TEXT_MAX_LENGTH=300 # for error msg
TEXT_CHAR_REPLACEMENT=' '
TEXT_SUFIX='...'
LOGGER_EMPTY_PLACEHOLDER='-' # when no content of the cell, use it to write to the cell

FLAG_URL='-u'
FLAG_PASS='-P'
FLAG_USER='-U'
FLAG_REDO='-r'
FLAG_HELP='-h'
FLAG_HELPS=['-h', '-help', '--help', '--h']

FLAG_START_INDEX='-s'
FLAG_END_INDEX='-e'
